### ISSUE TITLE
Python plugins global "skeleton" undefined

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos-plugins#3]
Happens for me when using the pathMeasure.py plugin. Where is this supposed to come from?

**Comment by Optiligence** [comment]
KNOSSOS creates this when it is started. 
is there any meaningful output suggesting that this didn’t happen?

**Comment by orenshatz** [comment]
I relocated knossos python interfaces into a dedicated python module,
you need to update your plugins as well.
