### ISSUE TITLE
can't import plugins in Knossos 5.0

### ISSUE THREAD

**Issue by Vanwalleghem** [knossos-project/knossos-plugins#4]
Hi, I just started playing around with Knossos, it looks great but I have issues with the plugins.
When I try to import the watershed plugin it gives me an error, in the python interpreter it looks like :
```Python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/Users/XXXXXX/AppData/Local/MPIN/KNOSSOS 5.0/knossos_plugins\watershedCubeSegmentor.py", line 3, in <module>
    import DatasetUtils, numpy, os, re, string, sys, traceback, time
ImportError: No module named DatasetUtils
```

Looking through your code, I guess you changed `DatasetUtils.py` to `knossosdataset.py`, so simply replacing it should work. I did try that, but then I got an
```Python
ImportError: No module named builtins
```
which is strange since I have python 3 and future installed in my python 2.7 install. builtins imports well from the anaconda prompt (I'm on windows 64).

**Comment by jmrk84** [comment]
Hi Yassum,
thanks for reminding us to update the plugin, it was not used in a while and more small issues might show up. The name and structure of Datasetutils was changed, and your fix is correct for this issue. The import error seems strange, given that it works in anaconda. Can you try to import other modules that are for sure only available in the anaconda environment from the interpreter command line in knossos? These issues are usually interpreter installation related, i.e. sometimes there are multiple interpreters, and the one you want to use with knossos is not the system default one.

Apart from this, please be aware that this plugin requires a (e.g. CNN generated) boundary map of your data that resides in knossos format somewhere accessible for the plugin. If you plan on using knossos for a segmentation workflow, we suggest you send us an email (knossos-team@mpimf-heidelberg.mpg.de) or outline your requirements here, we can then provide optimal support.

**Comment by my-tien** [comment]
It is possible to print the path to the used python interpreter from inside the KNOSSOS python console:
    
    import os
    os.path.dirname(os.__file__)

**Comment by Vanwalleghem** [comment]
Hey,
thanks for the quick answer, I'll send you an email today (Australia time) since we'd like to do some segmentation and I have some other questions regarding your software.

To go back to the issue I did have a look at the python interpreter and it uses Anaconda
```Python
py> import os
py> os.path.dirname(os.__file__)
'd:\\Continuum\\Anaconda2\\Lib'
```
But it still bugged out when doing `import builtins`. Restarting did not change that and I can still import it through the anaconda prompt.
Looking at the path gave me
```Python
py> sys.path
['C:\\WINDOWS\\system32\\python27.zip', 'd:\\Continuum\\Anaconda2\\Lib', 'd:\\Continuum\\Anaconda2\\DLLs', 'C:\\Python27\\Lib', 'C:\\Python27\\DLLs', 'C:\\Python27\\Lib\\lib-tk', 'C:\\Program Files\\MPIN\\KNOSSOS 5.0', 'C:\\Python27', 'C:\\Python27\\lib\\site-packages', 'C:/Users/XXXX/AppData/Local/MPIN/KNOSSOS 5.0/knossos_plugins', '']
```
In the end what worked was using `sys.path.append('D:\\Continuum\\Anaconda2\\Lib\\site-packages')`
It seems that somehow it was not going further that `\\Lib`

**Comment by Optiligence** [comment]
The plugins have been updated in regards to `KnossosDataset`. 
For your anaconda case, it’s probably a good idea to make the python installation in `C:/Python27` disappear.
